## Import libraries

In [1]:
# Note: v0.5.0 was the latest version available as of 31 December 2021
! pip install diffprivlib==0.5.0

     |████████████████████████████████| 87 kB 2.6 MB/s 
     |████████████████████████████████| 38.1 MB 1.4 MB/s 
  Created wheel for diffprivlib: filename=diffprivlib-0.5.0-py3-none-any.whl size=162302 sha256=f84c01e450e577321e9e2fd0449afb779443b8b0235a23295efd22bd96d673e4
  Stored in directory: /root/.cache/pip/wheels/e3/06/66/53eecc576e61a914f03ad5caee627823eb857225cb84aeb6d2
Successfully built diffprivlib
  Attempting uninstall: scipy
    Found existing installation: scipy 1.4.1
    Uninstalling scipy-1.4.1:
      Successfully uninstalled scipy-1.4.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.


In [2]:
from diffprivlib.tools.utils import sum
import matplotlib.pyplot as plt
import numpy as np

## Create datasets, and get the sums of these datasets

In [3]:
start_dataset = 0 * np.ones(4)
x_new = np.append(start_dataset,1)
y_new = np.append(start_dataset,0)

In [4]:
print(x_new)
print(y_new)

[0. 0. 0. 0. 1.]
[0. 0. 0. 0. 0.]


In [5]:
sum_thing = np.sum(x_new)
print(sum_thing)

sum_thing_2 = np.sum(y_new)
print(sum_thing_2)

print(sum_thing-sum_thing_2)


1.0
0.0
1.0


## Run bounded sum 10,000 times to see how readily we can tell the difference between these datasets

For a 17-row dataset, we can tell which dataset is which w.p. $\approx \frac{9999}{10,000}$. Crazy!!!

In [6]:
num_vals_power = 6 # means our start array is length 2**num_vals_power = 4. Works for vals \in [2,6]

start_dataset = 0 * np.ones(2**num_vals_power)
x_new = np.append(start_dataset,1)
y_new = np.append(start_dataset,0)

lower = (1+((2**(-53+num_vals_power)-2**(-52))))*0.5
upper = (1+(2**(-53+num_vals_power)))*0.5
eps_val = 1000

arr_1_ans = []
for _ in range(1000):
  arr_1_ans.append(sum(x_new, epsilon=eps_val, bounds = (lower, upper) ))

arr_2_ans = []
for _ in range(1000):
  arr_2_ans.append(sum(y_new, epsilon=eps_val, bounds = (lower, upper) ))

In [7]:
# print the frequency of each answer

the_ans = np.unique(arr_1_ans, return_counts = True)
print(the_ans[0][0])

the_ans = np.unique(arr_2_ans, return_counts = True)
print(the_ans[0][0])

32.50000000000023
32.50000000000022


In [8]:
sum(y_new, epsilon=0.00000001, bounds = (1, 1) )

65.0

In [9]:
y_new

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
arr_1_ans[0]-arr_2_ans[1]

7.105427357601002e-15

In [11]:
2**-48

3.552713678800501e-15